### ISSUE TITLE
Zombie bots passing through barricades (seemingly not having collision)

### ISSUE THREAD

**Issue by ComradeBlue1337** [Dadido3/D3bot#99] opened 2023-06-01 23:21 UTC
For some odd reason, some bots will simply phase through barricades, seemingly not having any collisions. It feels very game-breaking and I have no idea how to fix it. I also don't know what causes it and I haven't seen any errors pop up. It just happens at random intervals but happens often.

Is it related to navmeshes? Or maybe conflicting addons? When I play ZS either solo or with a friend I usually disable all other addons just leaving ULX, ULib, ZS ULX Commands and a few others that don't alter the game at all

I haven't seen anyone mentioning this issue here so I decided to do it myself

**Comment by ComradeBlue1337** [comment] 2023-06-01 23:26
Also, just thought I'd mention this; I'm also using the Github version of ZS and not the official workshop version as that one is broken. Maybe this could be part of the problem?

**Comment by Dadido3** [comment] 2023-06-03 22:22
I have heard of similar issues before, there even is a pull request (#36) that should prevent bots phasing through barricades once and for all (which seemingly does not work in your case).

The problem seems to occur in some versions of the gamemode, and doesn't in others. [Dadido3/zombiesurvival](https://github.com/Dadido3/zombiesurvival) should work fine, but it's an older ZS version.

I haven't really looked into the issue yet, and i don't have much time to do so at the moment. Which version of ZS are you using exactly? The [JetBoom/zombiesurvival ](https://github.com/JetBoom/zombiesurvival) one?

**Comment by ComradeBlue1337** [comment] 2023-06-04 16:57
> 

Yep, it's Jetboom's github one. It seems to be the latest and fixed version and it's odd that that's what could be breaking D3bot

**Comment by ComradeBlue1337** [comment] 2023-06-04 16:58
> I haven't really looked into the issue yet, and i don't have much time to do so at the moment. Which version of ZS are you using exactly? The [JetBoom/zombiesurvival ](https://github.com/JetBoom/zombiesurvival) one?
>

Yep, it's Jetboom's github one. It seems to be the latest and fixed version and it's odd that that's what could be breaking D3bot

**Comment by Antizombie** [comment] 2023-06-14 08:43
I have the same problem. Sometimes occurs.
Here is the moment that was captured.
Everything happens the same way without any errors. It seems that this was seen only with bots.
[zs_cabin_v7_2020-8-24_08-32-53.zip](https://github.com/Dadido3/D3bot/files/11743584/zs_cabin_v7_2020-8-24_08-32-53.zip)

**Comment by Sigilmare** [comment] 2023-07-10 15:41
This is because the bots get stuck in the barricade phasing mode even when they are zombie. It is caused when the bots spawn into the server.

One fix is to force-kick all bots after a new round starts, or manually set all bots to stop barricade phasing by using Player:SetBarricadeGhosting.

**Comment by ComradeBlue1337** [comment] 2023-07-10 18:51
> Thanks a lot for that hint. I now call SetBarricadeGhosting every time a new bot spawns, or every time a survivor bot is moved to the zombie team.
> 
> From looking into the ZS gamemode, it seems that ZS versions with sigils are affected. When survivors spawn on sigils the gamemode sets barricade ghosting to true, which then doesn't seem to be reset when i move these players into the zombie team by killing them. I probably never stumbled across this issue because i either tested ZS version without sigils, or versions that don't have sigil collision.
> 
> It would be nice if someone could confirm that this fix works.

I shall test it!

**Comment by Sigilmare** [comment] 2023-07-10 19:50
> 

it should work because I've disabled BarricadeGhosting myself whenever humans spawned inside of sigils and completely disabled humans getting teleported to sigils.

I will boot up a server and have a play-around with it. Glad I was able to help!

**Comment by Sigilmare** [comment] 2023-07-10 20:08
Another thing you can do is check if a bot is barricade ghosting and then proceed to disable barricade ghosting instead of calling Player:SetBarricadeGhosting(false) on bots that already have it disabled. #101

**Comment by Dadido3** [comment] 2023-07-10 20:12
Alright, that makes sense. Even though that doesn't happen that often, but it's a small optimization.

**Comment by ComradeBlue1337** [comment] 2023-07-10 20:55
Just tested myself and sadly the first zombie bot that spawned already phased through my cade. Though I was using the update from this commit: https://github.com/Dadido3/D3bot/commit/5f9991899f2361ed3aa663dd4e7a2511c43f0722

Maybe now with the latest change adding a check it might be fixed

**Comment by ComradeBlue1337** [comment] 2023-07-10 21:13
> Just tested myself and sadly the first zombie bot that spawned already phased through my cade. Though I was using the update from this commit: [5f99918](https://github.com/Dadido3/D3bot/commit/5f9991899f2361ed3aa663dd4e7a2511c43f0722)
> 
> Maybe now with the latest change adding a check it might be fixed

Just did a test again with 7 bots. All seemed to work okay and they didn't phase through anything. Hopefully it is indeed fixed now but to confirm it I'd probably have to try and test a few more times

**Comment by Sigilmare** [comment] 2023-07-10 21:45
I know a potential fix, hold on.

**Comment by Sigilmare** [comment] 2023-07-10 21:52
May have fixed the issue by calling it on the very next frame to ensure it gets called last. #102

**Comment by Dadido3** [comment] 2023-07-10 22:10
@ComradeBlue1337 can you test the latest change from Sigilmare?

**Comment by Antizombie** [comment] 2023-07-11 12:24
I suppose that this bug is occurring here:
https://github.com/JetBoom/zombiesurvival/blob/277e5c044c6aeab10bc5c9aeea4c987311e6eebe/gamemodes/zombiesurvival/gamemode/init.lua#L2214

But I am unable to consistently reproduce this bug in order to verify if it is the one causing this effect.

**Comment by Dadido3** [comment] 2023-07-11 12:59
The fix from Sigilmare should solve this, even though it may need to call `SetBarricadeGhosting(false)` a few more frames later (instead of the next frame).
A better fix would be to check if any zombie bot is in ghosting mode and then disable that, but first we should figure out what's really causing it to happen.

Can you place this code snippet somewhere on the server side (`sv_***.lua`).
It checks the ghosting state every second, and will print if a bot is in ghosting mode or changed its collision group (I have not yet tested the code):
``` lua
timer.Create("Bot ghosting debug", 1, 0, function()
	local bots = player.GetBots()
	for _, bot in ipairs(bots) do
		if bot:GetBarricadeGhosting() then
			bot:Say(string.format("I'm in barricade ghosting mode! Collision groups: %d", bot:GetCollisionGroup()))
		end

		if bot.__OldCollisionGroup ~= bot:GetCollisionGroup() then
			bot:Say(string.format("My collision group changed from %d to %d", bot.__OldCollisionGroup, bot:GetCollisionGroup()))
			bot.__OldCollisionGroup = bot:GetCollisionGroup()
		end
	end
end)
```

This should help to test if the problem is due to barricade ghosting, or some other reason that changed/broke the collision group.

**Comment by ComradeBlue1337** [comment] 2023-07-13 23:07
> @ComradeBlue1337 can you test the latest change from Sigilmare?

Oh sorry I forgot to check here
Sure will.

**Comment by ComradeBlue1337** [comment] 2023-07-14 20:49
> @ComradeBlue1337 can you test the latest change from Sigilmare?

I played with the mod a few rounds today and no bot phased through barricades. I think the bug might finally be fixed

**Comment by Dadido3** [comment] 2023-07-14 20:53
Alright, gonna close this for now. If you stumble upon the bug again, just write here

**Closed by Dadido3** 2023-07-14 20:53 UTC
Labels: bug
